import { ProductoCompra } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { NavBar } from "../components/NavBar";
import VentanaAgregar from "../components/ventanaAgregar";
import VentanaEditar from "../components/ventanaEditar";
import slugify from "react-slugify";
import { useRouter } from "next/router";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [cartItems, setCartItems] = useState([]);
  const [productos, setProductos] = useState<ProductoCompra[]>([]);
  const [productosCarrito, setProductosCarrito] = useState([]);
  const [ventanaAbierta, setVentanaAbierta] = useState<boolean>(false);

  const data = trpc.productos.verProductos.useQuery([], {
    onSuccess(productos) {
      setProductos(productos);
    },
  });

  console.log(productosCarrito, "esto es data");

  const { mutate: borrarProducto } = trpc.productos.borrarProducto.useMutation({
    onSuccess(productoCompra) {
      setProductos((prev) =>
        prev.filter((producto) => producto.id !== productoCompra.id)
      );
    },
  });
  const editarProducto = trpc.productos.editarProducto.useMutation({});
  const { asPath } = useRouter();

  return (
    <>
      <Head>
        <title>CRUD APP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {ventanaAbierta && (
        <VentanaAgregar
          setProductos={setProductos}
          setVentanaAbierta={setVentanaAbierta}
        />
      )}

      <NavBar />
      <main className="mx-auto my-12 max-w-3xl">
        <div className="mb-5 flex justify-between">
          <h2 className="text-2xl font-semibold">Lista de productos</h2>
          <button
            onClick={() => setVentanaAbierta(true)}
            className="rounded-md bg-black p-2 text-sm text-white transition hover:bg-gray-600"
          >
            Añadir producto
          </button>
        </div>
        <hr className="mb-5" />

        <div className="mb-10 grid grid-cols-4 gap-4">
          {productos.map((producto) => {
            const { id } = producto;
            return (
              <div key={producto.id}>
                <h1 className="text-xs">id: {producto.id}</h1>
                <div className="max-w-sm overflow-hidden rounded shadow-lg">
                  <Link as={`${slugify(producto.id)}`} href={`/[slug]`}>
                    <div className="px-4 py-2">
                      <span className="font-thin">Nombre:</span>
                      <div className="mb-2 text-xl font-bold">
                        {slugify(producto.nombre)}
                      </div>
                      <h1>${producto.precio}</h1>
                      <h1>Disponibles: ({producto.stock})</h1>
                      <h3 className="font-thin">Descripción:</h3>
                      <p className="text-base text-gray-700">{producto.desc}</p>
                    </div>
                  </Link>
                  <div className="px-6 pt-4 pb-2">
                    <button
                      onClick={() =>
                        setProductosCarrito([
                          ...productosCarrito,
                          [producto.nombre],
                        ])
                      }
                      className="bg-black text-white"
                    >
                      Añadir al carrito
                    </button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
        <div>
          <h1>Productos en carrito </h1>
          <ul></ul>
          <hr />
          <h2>Total productos</h2>
          <h2></h2>
          <h2></h2>
          <h2></h2>
          <hr />
          <button>Checkout</button>
        </div>
      </main>
    </>
  );
};

export default Home;
