import { ProductoCompra } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { NavBar } from "../components/NavBar";
import VentanaAgregar from "../components/ventanaAgregar";
import VentanaEditar from "../components/ventanaEditar";
import { Routes, Route } from "react-router-dom";

import { trpc } from "../utils/trpc";
import Productos from "./home";

const Home: NextPage = () => {
  const [productos, setProductos] = useState<ProductoCompra[]>([]);
  const [productoEditado, setProductoEditado] = useState<ProductoCompra[]>([]);
  const [ventanaAbierta, setVentanaAbierta] = useState<boolean>(false);
  const [ventanaAbiertaEditar, setVentanaAbiertaEditar] =
    useState<boolean>(false);
  const [nuevoNombre, setNuevoNombre] = useState<string>("");
  const [nuevaDesc, setNuevaDesc] = useState<string>("");
  const [nuevoPrecio, setNuevoPrecio] = useState<string>("");
  const [idProducto, setIdProducto] = useState<string>("");
  const [sortOrder, setSortOrder] = useState("");

  const data = trpc.productos.verProductos.useQuery([], {
    onSuccess(productos) {
      setProductos(productos);
    },
  });

  const { mutate: borrarProducto } = trpc.productos.borrarProducto.useMutation({
    onSuccess(productoCompra) {
      setProductos((prev) =>
        prev.filter((producto) => producto.id !== productoCompra.id)
      );
    },
  });
  const editarProducto = trpc.productos.editarProducto.useMutation({});

  return (
    <>
      <Head>
        <title>CRUD APP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {ventanaAbierta && (
        <VentanaAgregar
          setProductos={setProductos}
          setVentanaAbierta={setVentanaAbierta}
        />
      )}
      {ventanaAbiertaEditar && (
        <VentanaEditar
          nuevoPrecio={nuevoPrecio}
          idProducto={idProducto}
          nuevoNombre={nuevoNombre}
          nuevaDesc={nuevaDesc}
          setProductoEditado={setProductoEditado}
          setVentanaAbiertaEditar={setVentanaAbiertaEditar}
        />
      )}
      <NavBar />
      <main className="mx-auto my-12 max-w-3xl">
        <Routes>
          <Route path="/" element={<Productos />} />
        </Routes>
      </main>
    </>
  );
};

export default Home;
